version: '3.8'

services:
  app:
    build:
      context: ./api # Diretório onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: fincheck-Backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/postgresql?schema=public"
      JWT_SECRET: "fincheckapi"
      RESET_PASSWORD_JWT_SECRET: "resetpasswordfincheckapi"
      FRONTEND_URL: "http://localhost:5173"
      EMAIL_USER: "email@example.com"
      EMAIL_PASSWORD: "emailexamplepassword"
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fincheck-Frontend
    ports:
      - "5173:3000"
    volumes:
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres-data:

